'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace lab_47_mvc_framework_demo

    Partial Public Class Category
        Public Property CategoryId As Integer
        Public Property CategoryName As String
    
        Public Overridable Property Users As ICollection(Of User) = New HashSet(Of User)
    
    End Class

End Namespace
