'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace lab_47_mvc_framework_demo

    Partial Public Class User
        Public Property UserId As Integer
        Public Property UserName As String
        Public Property DateOfBirth As Nullable(Of Date)
        Public Property isValid As Nullable(Of Boolean)
        Public Property CategoryId As Nullable(Of Integer)
    
        Public Overridable Property Category As Category
    
    End Class

End Namespace
