//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab_25b_rabbit_database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RabbitTable
    {
        public int RabbitTableId { get; set; }
        public string RabbitName { get; set; }
        public Nullable<int> RabbitAge { get; set; }
    }
}
